### ISSUE TITLE
Separate plugins from server

### ISSUE THREAD

**Issue by tokejepsen** [tokejepsen/ftrack-event-server#1]
This could be with environment variables, or maybe passing in a folder to the server.

**Comment by mkolar** [comment]
Both would work fine. I'd even go as far as to say that it could look for env var by default, but if you give it a folder as argument when running it, it'll use it instead of the env var. That way you could chose which you prefer or potentially use it for dev overrides and similar situations.

**Comment by tokejepsen** [comment]
Sounds good.
